# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-6.2

# Packages to be built
packages:
- '.'

# Extra dependencies not in resolver packages
extra-deps:
    # Needed for project build of ghc-mod
    - cabal-helper-0.6.3.1

docker:
  enable: false # Travis containerized builds don't support Docker yet
  repo: "fpco/stack-build"
